[[redirects]]
from = "/linkEcor"
to = "http://www.ecor.it/it/prodotti/le-terre-di-ecor/az--agr--emanuele-giordano"
status = 200
force = true

[[redirects]]
from = "/linkCuorebio"
to = "https://www.negozicuorebio.it/e/le-terre-di-ecor/azienda-agricola-giordano-emanuele"
status = 200
force = true